= System-Wide Requirements: Projekt - Weiterentwicklung der Mitgliederdatenbanken
Kristina Lapatanova <kristina.lapatanova@htw-dresden.de>; Erik Würfel <erik.wuerfel@t-online.de>
{localdatetime}
//include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt I4 Weiterentwicklung der Mitgliederdatenbank des StuRa spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem separaten Dokument festgehalten. <<link:use_case-model.adoc[]>>

== Systemweite funktionale Anforderungen
// Functional: Fähigkeiten, Interoperabilität, Sicherheit. Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz

Ausarbeitung eines Datenschutzkonzeptes, welches die Anforderungen jederzeit erfüllt:

F1: Die personenbezogenen Daten sollen vor unberechtigtem Zugriff geschützt sein. +
F2: Persistenz der Daten. Die eingegebenen Werte sollen validiert werden, der Wertebreich geprüft werden. 


== Qualitätsanforderungen für das Gesamtsystem
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen


=== Benutzbarkeit (Usability)
//Usability: Bedienbarkeit, Verständlichkeit, Erlernbarkeit. Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)

U1: Das Mitglied/ Der Admin sollte die Bedienung innerhalb eines Tages erlernen. +
U2: Ausführen einer Hauptfunktionalität darf nicht mehr als 10 Klicks beanspruchen. 
//Mit der Webseite wird eine intuitive Bedienung durch  gewährleistet.

=== Zuverlässigkeit (Reliability)
// Zuverlässigkeit beinhaltet die Fähigkeit des Produkts und/oder des Systems unter Stress und ungünstigen Bedingungen am laufen zu bleiben. Spezifizieren Sie Anforderungen für zuverlässige Akzeptanzstufen, und wie diese gemessen und evaluiert werden. Vorgeschlagene Themen sind Verfügbarkeit, Häufigkeit und Schwere von Fehlern und Wiederherstellbarkeit.

R1: * Datenbank soll einmal die Woche ein Backup machen. Maximal drei Versionen der Datenbank sollen gespeichert werden.

=== Effizienz (Performance)
// Performance (Leistung): Reaktionszeiten, Durchsatz, Genauigkeit. Die Performanz Charakteristiken des Systems sollten in diesem Bereich ausgeführt werden. Beispiele sind Antwortzeit, Durchsatz, Kapazität und Zeiten zum Starten oder Beenden.

P1: Das System muss für eine gleichzeitige Nutzung von 10 Nutzern ausgelegt sein. Dafür werden wir uns noch 5 weitere  +
P2: Die Ladezeiten einer neuen Seite sollte sich auf zwei Sekunden beschränken, unter der Voraussetzung einer 16Mbit/s-Anschlusses. +

=== Wartbarkeit (Supportability)
//Supportability (Unterstützbarkeit): Anpassungsfähigkeit, Wartbarkeit, Konfigurierbarkeit. Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.
 
S1: Das System soll einfach erweiterbar und wartbar sein. 

== Zusätzliche Anforderungen
=== Einschränkungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Ressourcenbegrenzungen - Speicherplatzbegrenzung auf 5MB pro Dokument, welches hochgeladen wird.
* Datenbank soll dreimal die Woche ein Backup machen. Maximal drei Versionen der Datenbank sollen gespeichert werden.

=== Rechtliche Anforderungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Nutzung von freien Lizenzen (Open Source)