= Projektplan: I4 Weiterentwicklung der Mitgliederdatenbank des StuRa
Manuela Ziesche <manuela.ziesche@htw-dresden.de>
{localdatetime}

== Einführung 

Dieser Plan zeigt Inhalt, sowie Meilensteine des *'I4 - Weiterentwicklung der Mitgliederdatenbank des StuRa'* Projektes. + 
 +
Alle *Risiken* wurden in der <<link:risk_list.adoc[]>>  aufgeführt. +
Die <<link:work_item_list.adoc[]>> beinhaltet alle *benutzten Tools und Werkzeuge*, die im Projekt gebraucht wurden.  + 
Die Dokumentation unseres Projektes umfassst ebenso die *Protokolle* von Meetings. #VERWEIS AUF ORDNER?# +
Außerdem gibt es für jede Iteration noch einen eigenen *Iterationsplan*: 
 +
<<link:iteration_plan01.adoc[]>> +
<<link:iteration_plan02.adoc[]>> +
//<<link:iteration_plan03.adoc[]>> +
//<<link:iteration_plan04.adoc[]>> +

== Projektorganisation

Die Arbeit wird in folgende Bereiche aufgegliedert, die wie folgt besetzt wurden.

- Projektmanagement: Manuela Ziesche + 
- Analyse: Kristina Lapatanova, Erik Würfel + 
- Architektur: Sebastian Matthäus, Benjamin Müller + 
- Entwicklung: Leander  Vasco Schwarze, Sabine Elisabeth Adam +
- Test: Bayu Anggi Saputra, Sebastian Matthäus + 

== Projektpraktiken

== Meilensteine des Projektes

.Iterationsphasen

|======
| *Phase* | *Iteration* | *Hauptziel* | *Iterationsstart* | *Iterationsende* | *Kalendertage*
| Inception | M0 | - Lifecycle Objective + 
- Vision| 30.11.2020 | 13.12.2020 | 14 Tage 
| Elaboration | M1 | | 14.12.2020 | | 
| Elaboration | M2 | | | | 
| Elaboration | M3 | - Abgabe der Dokumentation in PDF| | 31.01.2021 |


|====== 

== Deployment


== Erkenntnisse

