= Projektplan: I4 Weiterentwicklung der Mitgliederdatenbank des StuRa
Manuela Ziesche <manuela.ziesche@htw-dresden.de>
{localdatetime}
:toc: 
:toc-title: Inhaltsverzeichnis
:source-highlighter: highlightjs

== Einführung 
Dieser Plan zeigt Inhalt, sowie Meilensteine des *'I4 - Weiterentwicklung der Mitgliederdatenbank des StuRa'* Projektes. + 
 +
Alle *Risiken* wurden in der <<link:risk_list.adoc[]>>  aufgeführt. +
Die <<link:Work_Item_List.adoc[]>> beinhaltet alle *benutzten Tools und Werkzeuge*, die im Projekt gebraucht wurden.  + 
Die Dokumentation unseres Projektes umfassst ebenso *Protokolle* von Meetings. <<link:protocol[]>> +
Außerdem gibt es für jede Iteration noch einen eigenen *Iterationsplan*. Alle Iterationspläne sind in dem Ordner zu finden: <<link:iteration_plans[]>>. +
Der Projektstand nach jeder Iteration wird durch einen Screenshot des Essence Navigators hier festgehalten: 
<<link:essence_navigator_images[]>>. + 


== Projektorganisation
Die Arbeit wird in folgende Bereiche aufgegliedert, die wie folgt besetzt wurden.
* 3. Semester:
- Projektmanagement: Manuela Ziesche + 
- Analyse: Kristina Lapatanova, Erik Würfel + 
- Architektur: Benjamin Müller, Sebastian Matthäus + 
- Entwicklung: Leander Vasco Schwarze, Sabine Elisabeth Adam +
- Test: Bayu Anggi Saputra, Sebastian Matthäus + 

* 4. Semester:
- Projektmanagement: Manuela Ziesche (Backup: Sabine Elisabeth Adam) + 
- Deployment Engineer: Leander Vasco Schwarze (Backup: Sabine Elisabeth Adam)
- Analyse: Sabine Elisabeth Adam, Manuela Ziesche
- Architektur: Benjamin Müller, Sebastian Matthäus + 
- Entwicklung: Leander Vasco Schwarze, Sabine Elisabeth Adam +
- Test: Bayu Anggi Saputra, Sebastian Matthäus + 
- Technical Writer: Manuela Ziesche (Backup: alle anderen)

Diese Einteilung ist durch die jeweiligen Interessen und Vorkenntnisse der Mitglieder zustande gekommen. Wir haben alle Bereiche mit zwei Leuten besetzt, um möglichen Ausfall abzudecken. 

== Projektpraktiken
* Management Practices:
- Iterative Development 
- Risk-Value Lifecycle
- Whole Team

* Technical Practices:
- Shared Vision
- Use Case Driven Development


- Iterationen 3 Wochen lang
- Tools zur Organisation: +
    -> Trello +
    -> Essence Navigator
- Tools zur Dokumentation: +
    -> GitHub +
- Tools zur Kommunikation: +
    -> WhatsApp + 
    -> Discord + 


== Meilensteine des Projektes

.Iterationsphasen
|======
| *Phase* | *Iteration* | *Hauptziele* | *Iterationsstart* | *Iterationsende* | *Kalendertage* | *Notizen*
| *Inception* | M0 | -  | 30.11.2020 | 20.12.2020 | 21 Tage | 
| *Elaboration* | M1 | 
-| 21.12.2020 | 10.01.2021 | 21 Tage | - Phase über Weihnachten und Silvester
| *Elaboration* | M2 | -  | 11.01.2021 | 31.01.2021 | 21 Tage  | 
|====== 

== Deployment
Sobald das überarbeitete Projekt online geht, übergeben wir den Admins die Zugangsdaten. 


== Erkenntnisse
- Dokumente sollten von mehreren Personen kontrolliert/durchgeschaut werden, um Fehler zu erkennen und zu vermeiden
- das Zusammentragen von Ideen in der Gruppe ist sinnvoll
- ein/zwei wöchentliche Meetings sind praktisch um Fehler/Probleme frühzeitig anzusprechen