= Projektplan: I4 Weiterentwicklung der Mitgliederdatenbank des StuRa

== Einführung 

Dieser Plan zeigt Inhalt, sowie Meilensteine des *'I4 - Weiterentwicklung der Mitgliederdatenbank des StuRa'* Projektes. + 
 +
Alle _Risiken_ wurden in der <<link:risk_list.adoc[]>>  aufgeführt. +
Die <<link:work_item_list.adoc[]>> beinhaltet alle _benutzten Tools und Werkzeuge_, die im Projekt gebraucht wurden.  + 
Die Dokumentation unseres Projektes umfassst ebenso die Protokolle von Meetings. VERWEIS AUF ORDNER? +
Außerdem gibt es für jede Iteration noch einen eigenen Iterationsplan: 
 +
<<link:iteration_plan01.adoc[]>> +


== Projektorganisation

Die Arbeit wird in folgende Bereiche aufgegliedert, die wie folgt besetzt wurden.

- Projektmanagement: Manuela Ziesche + 
- Analyse: Kristina Lapatanova, Erik Würfel + 
- Architektur: Sebastian Matthäus, Benjamin Müller + 
- Entwicklung: Leander  Vasco Schwarze, Sabine Elisabeth Adam +
- Test: Bayu Anggi Saputra, Sebastian Matthäus + 

== Projektpraktiken

== Meilensteine des Projektes

.Iterationsphasen

|======
| *Phase* | *Iteration* | *Hauptziel* | *Iterationsstart* | *Iterationsende* | *Kalendertage*
| Inception | M0 | -Lifecycle Objective +
 -Ziel ist klar + | 30.11.2020 | 13.12.2020 | 14 Tage 
| Elaboration | M1 | | 15.12.2020 | | 
| Elaboration | M2 | | | | 
| Elaboration | M3 | | | |

|====== 

== Deployment


== Erkenntnisse

