= Projektplan: I4 Weiterentwicklung der Mitgliederdatenbank des StuRa
Manuela Ziesche <manuela.ziesche@htw-dresden.de>
{localdatetime}
:toc: 
:toc-title: Inhaltsverzeichnis
:source-highlighter: highlightjs

== Einführung 
Dieser Plan zeigt Inhalt, sowie Meilensteine des *'I4 - Weiterentwicklung der Mitgliederdatenbank des StuRa'* Projektes. Die Dokumente werden im Laufe der Projektumsetzung stetig erweitert oder um neue ergänzt. Der Projektplan dient zur Organisation und Transparenz innerhalb des Teams.
 +
Alle *Risiken* wurden in der <<link:risk_list.adoc[]>>  aufgeführt. +
Die <<link:Work_Item_List.adoc[]>> beinhaltet alle *benutzten Tools und Werkzeuge*, die im Projekt gebraucht wurden.  + 
Die Dokumentation unseres Projektes umfassst ebenso *Protokolle* von Meetings. <<link:protocol[]>> +
Außerdem gibt es für jede Iteration noch einen eigenen *Iterationsplan*. Alle Iterationspläne sind in dem Ordner zu finden: <<link:iteration_plans[]>>. +
Der Projektstand nach jeder Iteration wird durch einen Screenshot des Essence Navigators hier festgehalten: 
<<link:essence_navigator_images[]>>. + 


== Projektorganisation
=== Teammitglieder und Aufteilung
Das Team bestand im 3. Semester aus 8 Personen, im 4. Semester sind Erik Würfel und Kristina Lapatanova nicht mehr im Projekt dabei. 
Deswegen mussten die Stellen der Analysten neu besetzt werden.

| ===
| Person | Alter | Informationen | Rolle

| 

Die Arbeit wird in folgende Bereiche aufgegliedert, die wie folgt besetzt wurden.
* 3. Semester:
- Projektmanagement: Manuela Ziesche + 
- Analyse: Kristina Lapatanova, Erik Würfel + 
- Architektur: Benjamin Müller, Sebastian Matthäus + 
- Entwicklung: Leander Vasco Schwarze, Sabine Elisabeth Adam +
- Test: Bayu Anggi Saputra, Sebastian Matthäus + 

* 4. Semester:
- Projektmanagement: Manuela Ziesche (Backup: Sabine Elisabeth Adam) + 
- Deployment Engineer: Leander Vasco Schwarze (Backup: Sabine Elisabeth Adam)
- Analyse: Sabine Elisabeth Adam, Manuela Ziesche
- Architektur: Benjamin Müller, Sebastian Matthäus + 
- Entwicklung: Leander Vasco Schwarze, Sabine Elisabeth Adam +
- Test: Bayu Anggi Saputra, Sebastian Matthäus + 
- Technical Writer: Manuela Ziesche (Backup: alle anderen)

Diese Einteilung ist durch die jeweiligen Interessen und Vorkenntnisse der Mitglieder zustande gekommen. Wir haben alle Bereiche mit zwei Leuten besetzt, um einen möglichen Ausfall abzudecken. 

=== Arbeitsweise
- Iterationen 3 Wochen lang
- Tools zur Organisation: +
    -> Trello +
    -> Essence Navigator
- Tools zur Dokumentation: +
    -> GitHub +
- Tools zur Kommunikation: +
    -> WhatsApp + 
    -> Discord + 

Wir organisieren unseren Ablauf über ein Trello Board, in welches wir alle Aufgaben unter *To-Do*, *In Arbeit* oder *Bearbeitet* unterteilen. Außerdem werden da auch alle geplanten Termine festgehalten. 
Zu kleineren Absprachen oder Erinnerungen verwenden wir eine WhatsApp Gruppe. Dort werden auch neue Termine geplant, wenn wir dies nicht in einem eheren Meeting schon getan haben.
Die  Terminfindung klären wir meistens im Gespräch, doch wenn das mal nicht so einfach funktioniert, erstellt Sebastian eine Umfrage, wonach wir dann beispielsweise einen neuen Termin für ein Meeting finden.
Für diese Meetings haben wir uns für Discord entschieden. Dort hat Benjamin für unsere Gruppe einen eigenen Server erstellt und im Sprachkanal halten wir alle wöchentlichen Meetings ab. Auch die Meetings mit den Stakeholdern oder mit unserem Coach laufen über diesen Server. Das hat sich als sehr sinnvoll erwiesen, da man über eine Bildschirmübertragung Fragen an Dokumenten gleich dem gesamtem Team stellen kann. Aber auch Links landen da drin, damit nicht alle alleine suchen müssen. Das erspart uns innerhalb der Meetings wichtige Zeit.
Protokolle schreiben Sabine und Manuela mit, die wichtigsten landen auch im GitHub. Das wird ab der 4. Iteration auch geändert. Da sollen die Protokolle für alle Teammitglieder einsehbar sein. Dies klärt eventuell gleich offene, kleinere Fragen und man braucht in keine Diskussion zurückfallen.

In der fünften Iteration haben wir uns noch dazu entschieden, unseren Discord Server umzustrukturieren. Es gibt jetzt für alle Aufgabenbereiche jeweils Text- und Sprachkanal, um unseren Autausch organisierter zu halten. 

== Projektpraktiken

* Management Practices:
- Iterative Development 
- Risk-Value Lifecycle
- Whole Team

* Technical Practices:
- Shared Vision
- Use Case Driven Development

Wir arbeiten in dem gesamten Zeitraum des Open Unified Process. Da wir eine agile Entwicklung nutzen sollen, haben wir die großen Zeiträume in kleinere Zeiträume, Iterationen unterteilt und planen jede Iteration am Anfang gemeinsam. Wichtig hierbei sind unsere Ziele und unsere Aufgaben in der Iteration. Diese werden direkt eingeteilt und am Ende überprüfen wir die erledigten Aufgaben und erfolgreich gemeisterten Ziele in einem Teammeeting. 
In diesem gehen wir auch alle gemeinsam den Essence Navigator durch und bewerten die Iteration.
Wir haben uns für Iterationslängen von 3 Wochen entschieden. Anfangs wollten wir auch Iteration von zwei Wochen machen, doch uns ist aufgefallen, dass das für ein paar Ziele oder Aufgaben, die in der Iteration gemacht werden sollen, zu wenig Zeit ist. Außerdem haben wir so weniger Organisationsaufgaben und können uns auf deren ordentlliche Ausführung und auf alle anderen konzentrieren (bspw. Prototypen Entwicklung), da die Orga-Meeting viel Zeit rauben.

== Meilensteine des Projektes

.Iterationsphasen
|======
| *Phase* | *Iteration* | *Hauptziele* | *Iterationsstart* | *Iterationsende* | *Kalendertage* | *Notizen*
| *Inception* | M0 | -Erstes Meeting mit den Stakeholdern - Organsisation des Teams und Kennenlernen - Auftrag analysieren| 30.11.2020 | 20.12.2020 | 21 Tage | 
| *Elaboration* | M1 | 
- Visionserstellung | 21.12.2020 | 10.01.2021 | 21 Tage | - Phase über Weihnachten und Silvester
| *Elaboration* | M2 | -  | 11.01.2021 | 31.01.2021 | 21 Tage  | 
| *Construction* | M3 | | 29.03.2021 | 19.04.2021| 21 Tage
|====== 

== Ziele 
=== Kurzfristig
- strukturierte und organisierte Arbeitsweise im Team 
- Teammeetings für Aufgabenverteilung und Planung der weiteren Vorgehensweise nutzen
=== Langfristig
- Die Entwicklung einer funktionellen Datenbank, welche den Arbeitsprozess der Admins des StuRa sinnvoll vereinfacht.
- Eine zufriedenstellende Belegabgabe.
- durchgängig Spaß an dem Projekt/der Bearbeitung der einzelnen Aufgaben

== Deployment
Sobald die Zeit für unser Projekt abgelaufen ist, werden wir das gesammelt an den StuRa ausliefern. Wir werden außerdem Anleitungen zur weiteren Nutzung bereitstellen. 

== Erkenntnisse
- Dokumente sollten von mehreren Personen kontrolliert/durchgeschaut werden, um Fehler zu erkennen und zu vermeiden -> 4-Augen-Prinzip
- das Zusammentragen von Ideen in der Gruppe ist sinnvoll
- Ein/zwei wöchentliche Meetings sind praktisch um Fehler/Probleme frühzeitig anzusprechen. 
- "Stille" Arbeitsgruppen, d.h. 2-3 Personen treffen sich über einen Sprachkanal und bearbeiten getrennt Aufgaben. So kann man schneller wegen Formulierungsfragen oder Verständisproblemen einen Zweiten fragen und man motiviert sich gegenseitig. 
- Protokollführung ist wichtig!