= Projektplan: I4 Weiterentwicklung der Mitgliederdatenbank des StuRa

== Einführung 

Dieser Plan zeigt Inhalt, sowie Meilensteine des 'I4 - Weiterentwicklung der Mitgliederdatenbank des StuRa' Projektes. +
Alle Risiken wurden in der sogenannten 'Risk List' aufgeführt. +
Die 'Work Items List' beinhaltet alle benutzten Tools und Werkzeuge, die im Projekt gebraucht wurden. + 
Außerdem gibt es für jede Iteration noch einen eigenen Iterationsplan. 

== Projektorganisation

Die Arbeit wird in folgende Bereiche aufgegliedert, die wie folgt besetzt wurden.

-Projektmanagement: Manuela Ziesche + 
-Analyse: Kristina Lapatanova, Erik Würfel + 
-Architektur: Sebastian Matthäus, Benjamin Müller + 
-Entwicklung: Leander  Vasco Schwarze, Sabine Elisabeth Adam +
Test: Bayu Anggi Saputra, Sebastian Matthäus + 

== Projektpraktiken

== Meilensteine des Projektes

.Iterationsphasen

|======
| *Phase* | *Iteration* | *Hauptziel* | *Iterationsstart* | *Iterationsende* | *Kalendertage*
| Inception | M0 | | 23.11.2020 | 06.12.2020 | 14 Tage 
| Elaboration | M1 | | 07.12.2020 | | 
| Elaboration | M2 | | | | 
| Elaboration | M3 | | | |

|====== 

== Deployment


== Lessons Learned?

